import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowRight } from 'lucide-react';
const performanceData = [60, 80, 40, 20, 90, 100, 70];
export function GhostTradingWidget() {
    return (_jsxs(Card, { className: "glassmorphism widget-hover", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-lg font-bold", children: "Ghost Trading System" }), _jsx("div", { className: "w-3 h-3 bg-green-500 rounded-full animate-pulse" })] }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Active Strategy" }), _jsx("div", { className: "font-medium", children: "EUR/USD Momentum Alpha" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Daily P&L" }), _jsx("div", { className: "text-xl font-bold text-green-500", children: "+$2,847.50" })] }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Open Trades" }), _jsx("div", { className: "text-xl font-bold", children: "7" })] })] }), _jsx("div", { className: "h-16 bg-muted rounded-lg flex items-end justify-center space-x-1 p-2", children: performanceData.map((height, index) => (_jsx(motion.div, { className: `w-2 rounded-t ${height > 50 ? 'bg-green-500' : 'bg-red-500'}`, style: { height: `${height}%` }, initial: { height: 0 }, animate: { height: `${height}%` }, transition: { delay: index * 0.1, duration: 0.5 } }, index))) }), _jsxs(Button, { variant: "link", className: "w-full text-primary hover:text-primary/80 text-sm p-0", children: ["View GhostView Details ", _jsx(ArrowRight, { className: "w-4 h-4 ml-1" })] })] })] }));
}
