import * as cron from 'node-cron';
import { storage } from './storage';
import { getGeminiPDFService } from './gemini-pdf-service';
const geminiPDFService = getGeminiPDFService();

class SchedulerService {
  private isInitialized = false;

  init() {
    if (this.isInitialized) {
      console.log('Scheduler already initialized');
      return;
    }

    console.log('Initializing scheduler service...');
    
    // Generate PDF report with Gemini at 7:00 AM EST (12:00 UTC)
    cron.schedule('0 12 * * *', async () => {
      console.log('Generating AI-powered PDF report at 7:00 AM EST...');
      await this.generateAIPDFReport();
    }, {
      name: 'generate-ai-pdf-report',
      timezone: "America/New_York"
    });

    // Upload and notify PDF report at 7:30 AM EST (12:30 UTC)
    cron.schedule('30 12 * * *', async () => {
      console.log('Uploading and notifying PDF report at 7:30 AM EST...');
      await this.uploadAndNotifyPDFReport();
    }, {
      name: 'upload-notify-pdf-report',
      timezone: "America/New_York"
    });

    // Schedule daily reports at 7:30 AM EST (12:30 UTC winter, 11:30 UTC summer)
    // Using 12:30 UTC to cover EST winter time
    cron.schedule('30 12 * * *', async () => {
      console.log('Generating daily report at 7:30 AM EST...');
      await this.generateDailyReport();
    }, {
      timezone: 'UTC'
    });

    // Schedule daily notifications at 7:30 AM EST
    cron.schedule('30 12 * * *', async () => {
      console.log('Sending daily notifications at 7:30 AM EST...');
      await this.sendDailyNotifications();
    }, {
      timezone: 'UTC'
    });

    // Cleanup task for old notifications (daily at midnight UTC)
    cron.schedule('0 0 * * *', async () => {
      console.log('Cleaning up old notifications...');
      await this.cleanupOldNotifications();
    }, {
      timezone: 'UTC'
    });

    this.isInitialized = true;
    console.log('Scheduler service initialized successfully');
  }

  private async generateDailyReport() {
    try {
      const today = new Date();
      const reportContent = await this.generateReportContent();
      
      const report = await storage.createDailyReport({
        title: 'Daily Market Analysis Report',
        description: 'Automated daily analysis of financial markets and trading recommendations',
        reportDate: today,
        content: reportContent
      });

      console.log(`Daily report generated with ID: ${report.id}`);
      
      // Create a notification to inform users of the new report
      await storage.createNotification({
        title: 'New Daily Report Available',
        content: `The daily analysis report for ${today.toLocaleDateString('en-US')} is now available.`,
        message: `Check the latest market analysis and recommendations in your dashboard.`,
        type: 'info',
        isGlobal: true
      });

    } catch (error) {
      console.error('Error generating daily report:', error);
    }
  }

  private async generateReportContent(): Promise<string> {
    // Here you can integrate your AI logic to generate report content
    const today = new Date();
    const dateStr = today.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `
# Daily Analysis Report - ${dateStr}

## Executive Summary
Financial market analysis and recommendations for the day.

## Major Currency Analysis
- EUR/USD: Technical and fundamental analysis
- GBP/USD: Trends and key levels
- USD/JPY: Short-term outlook

## Important Economic Events
Calendar of major economic announcements for the day.

## Trading Recommendations
Signals and opportunities identified by our AI.

## Risk Management
Advice for portfolio and risk management.

---
*Report automatically generated by Helix AI at ${today.toLocaleTimeString('en-US')}*
    `.trim();
  }

  private async sendDailyNotifications() {
    try {
      // Notification for the start of the trading day
      await storage.createNotification({
        title: 'Markets Open - Have a Great Trading Day!',
        content: 'Markets are open. Check your dashboard for the latest analysis.',
        message: 'Stay informed about trading opportunities with our real-time analysis.',
        type: 'info',
        isGlobal: true
      });

      console.log('Daily notifications sent successfully');
    } catch (error) {
      console.error('Error sending daily notifications:', error);
    }
  }

  private async cleanupOldNotifications() {
    try {
      const deletedCount = await storage.cleanupOldNotifications(30);
      console.log(`Cleanup completed: ${deletedCount} old notifications removed`);
    } catch (error) {
      console.error('Error during cleanup:', error);
    }
  }

  private async generateAIPDFReport() {
    try {
      console.log('🤖 Starting AI-powered PDF report generation...');
      
      const service = geminiPDFService;
      const reportData = await service.generateDailyReport();
      const pdfBuffer = await service.generateBrandedPDF(reportData);
      
      const today = new Date();
      const now = new Date();
      const dateStr = now.toISOString().split('T')[0];
      const timeStr = `${now.getHours().toString().padStart(2, '0')}-${now.getMinutes().toString().padStart(2, '0')}`;
      const filename = `helix-daily-report-${dateStr}_${timeStr}.pdf`;
      
      const filePath = await service.savePDFToUploads(pdfBuffer, filename);
      
      console.log(`✅ AI PDF report generated and saved: ${filePath}`);
      
      // Store report information for later upload
      await storage.createDailyReport({
        title: 'Helix Daily Fundamental Report',
        description: 'AI-generated comprehensive forex market analysis and insights',
        reportDate: today,
        content: reportData.content,
        pdfPath: filePath,
        pdfUrl: filePath,
        filename: filename
      });
      
    } catch (error) {
      console.error('❌ Error generating AI PDF report:', error);
      
      // Create error notification
      await storage.createNotification({
        title: 'Report Generation Error',
        content: 'An error occurred while generating the daily AI report.',
        message: 'The technical team has been notified. A report will be generated manually.',
        type: 'error',
        isGlobal: true
      });
    }
  }

  private async uploadAndNotifyPDFReport() {
    try {
      console.log('📤 Starting PDF upload and notification...');
      
      const today = new Date();
      const reports = await storage.getDailyReports(today);
      
      if (reports.length === 0) {
        console.log('No PDF report found for upload');
        return;
      }
      
      const latestReport = reports[0];
      
      // Create notification with PDF report link
      await storage.createNotification({
        title: '📊 New AI Analysis Report Available',
        content: `The AI-generated daily analysis report for ${today.toLocaleDateString('en-US')} is now available.`,
        message: `Discover the latest market analysis, trading recommendations and insights generated by our advanced AI. Report available for download.`,
        type: 'success',
        isGlobal: true,
        metadata: {
          pdfPath: latestReport.pdfPath,
          filename: latestReport.filename,
          reportType: 'ai-generated'
        }
      });
      
      console.log(`✅ PDF report uploaded and notification sent: ${latestReport.filename}`);
      
    } catch (error) {
      console.error('❌ Error uploading PDF report:', error);
      
      await storage.createNotification({
        title: 'Report Upload Error',
        content: 'An error occurred while uploading the daily report.',
        message: 'Please contact the technical team.',
        type: 'error',
        isGlobal: true
      });
    }
  }

  // Method to manually test report generation
  async testDailyReport() {
    console.log('🧪 Testing daily report generation...');
    await this.generateDailyReport();
    console.log('✅ Daily report test completed');
  }

  // Method to manually test notifications
  async testDailyNotifications() {
    console.log('🧪 Testing daily notifications...');
    await this.sendDailyNotifications();
    console.log('✅ Daily notifications test completed');
  }

  // Method to manually test AI PDF report generation
  async testAIPDFReport() {
    console.log('🧪 Testing AI PDF report generation...');
    try {
      await this.generateAIPDFReport();
    } catch (error) {
      if (error instanceof Error && error.message.includes('GOOGLE_GEMINI_API_KEY')) {
        console.log('⚠️ Skipping AI PDF test - Google Gemini API key not configured');
        return;
      }
      throw error;
    }
    console.log('✅ AI PDF report test completed');
  }

  // Method to manually test PDF report upload
  async testPDFUpload() {
    console.log('🧪 Testing PDF report upload...');
    try {
      await this.uploadAndNotifyPDFReport();
    } catch (error) {
      if (error instanceof Error && error.message.includes('GOOGLE_GEMINI_API_KEY')) {
        console.log('⚠️ Skipping PDF upload test - Google Gemini API key not configured');
        return;
      }
      throw error;
    }
  }
}

export const scheduler = new SchedulerService();